### ISSUE TITLE
Whole Exome Data

### ISSUE THREAD

**Issue by fitbio** [marcos-diazg/musica#28]
Can Musica be used for analysis of Whole Exome Data.??

**Comment by fitbio** [comment]
Thank you. I will try it out today. Thank you for your kind reply.

**Comment by fitbio** [comment]
Thank you. I have used musica for my exome samples. I set the option of whole exome sequencing for  my analysis. But regarding the Mutational signatures from my Exome samples, does the trinucleotide frequency of the exomes  get normalized to the genome level to compare my signatures with cosmic samples? Because when I set "study" as whole exome or whole genome  except Somatic prevalance results, the other results are exactly the same. Does a normalization step of exome to genome actually occur?

**Comment by marcos-diazg** [comment]
As you commented, MuSiCa just takes the type of analysis input option to correctly calculate the somatic mutational prevalence. Regarding mutational signatures analysis, it makes use of MutationalPatterns package. To my knowledge, it does not perform any kind of normalization. Thank you for your feedback!
