### ISSUE TITLE
Stopped after clicking "Run" button

### ISSUE THREAD

**Issue by archerrish** [marcos-diazg/musica#29]
131: stop
  130: mut_matrix
  129: <reactive:mut_mat> [/home/xie/Workspace/R/musica/server.R#261]
  113: mut_mat
  111: <reactive:fit_res> [/home/xie/Workspace/R/musica/server.R#278]
   95: fit_res
   92: renderUI [/home/xie/Workspace/R/musica/server.R#458]
   91: func
   78: origRenderFunc
   77: output$selected_samples
    1: runApp

Installed from git 
OS: Ubuntu 18.04
R version 3.4.4 (2018-03-15) -- "Someone to Lean On"

**Comment by marcos-diazg** [comment]
Hello and thank you for using the app! Try to downgrade shiny package to 1.0.5 version. Sorry for the inconveniences.

**Comment by archerrish** [comment]
@marcos-diazg I had downgraded the shiny to 1.0.5, but it didn't work.

**Comment by marcos-diazg** [comment]
Could you please give me a more explanatory report of your error message?

Which type of file are you using? Just one, or more than one file at a time? Have you tried different reference genomes? Have you installed all of the required dependencies?

Have you tried to use the [online app](http://bioinfo.ciberehd.org/GPtoCRC/en/tools.html) with the same files that you are using in your own installation of MuSiCa?

**Comment by marcos-diazg** [comment]
Please try the new realease of MuSiCa (v1.0), which is fully up-to-date with all the required dependencies (including new Shiny 1.1.0). It's available [here](https://github.com/marcos-diazg/musica/releases)!
