### ISSUE TITLE
Downloaded plots have cut off info

### ISSUE THREAD

**Issue by magdaaverte** [marcos-diazg/musica#33]
Hi,
first of all thank you for this amazing, intuitive tool. It's so great to be able to detect mutational signature and compare to existing ones using one button! 
I would like to report an issue regarding downloaded plots. It seems that some information is cut off, e.g.
prof96_plot: n in Relative contribution, the name of the file if it's longer than ~10 characters
signatures_plot: the name of the file on the bottom, values on the scale are not displayed fully
comparison_with_cancers: names of signatures are pretty tight (that's lower priority) but the names of cancers like nasopharyngeal carcinoma or oral gingivo buccal squamous (cell carcinoma) are cut off, also the name of the file if it's as long
I am using only one sample.
Thanks so much!
[Musica_infoCutOff.pdf](https://github.com/marcos-diazg/musica/files/2314658/Musica_infoCutOff.pdf)

**Comment by magdaaverte** [comment]
Thank you, that is a good workaround for now. Good luck with the application!

**Comment by marcos-diazg** [comment]
Closed by inactivity and focus on new projects.
