### ISSUE TITLE
Problem Installing ShinySky

### ISSUE THREAD

**Issue by sidhomj** [marcos-diazg/musica#35]
When trying to install dependencies, there is a problem installing ShinySky. 

Also, web-app is down. 

* installing *source* package 'shinysky' ...
** R
** inst
** byte-compile and prepare package for lazy loading
Error : (converted from warning) package 'shiny' was built under R version 3.5.3
ERROR: lazy loading failed for package 'shinysky'
* removing 'C:/Users/lcheung1/Documents/R/R-3.5.2/library/shinysky'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/lcheung1/AppData/Local/Temp/RtmporL0QN/file13e6e062211299/shinysky_0.1.2.tar.gz’ had non-zero exit status

**Comment by marcos-diazg** [comment]
Hi!

First of all thanks for using our app! According to your error file it seems that you need to upgrade shiny package. Try to reinstall from scratch all the dependencies of musica. Using a package manager such as conda could be a great option too.

Regarding the web app, it is going to be down during a short period. Sorry for the inconveniences.

**Comment by marcos-diazg** [comment]
I have tested shinysky version 0.1.2 and it worked perfectly with shiny version 1.3.2. I have used `runGitHub("musica", "marcos-diazg")` command to launch the app from RStudio.

Try this and let me know if ir works for you. Have a great day!

**Comment by sidhomj** [comment]
Will just wait for webapp to be up again. How long will it be expected to be down? thanks!

**Comment by marcos-diazg** [comment]
You have experienced a problem in our web server. We expect the app to be up in one or two weeks. Thanks!

**Comment by marcos-diazg** [comment]
Web app is up again! Thanks for your patience!
