### ISSUE TITLE
Could not identify file types except vcfs

### ISSUE THREAD

**Issue by Shukyo** [marcos-diazg/musica#41]
While MAF or TSV type was chosen, the program still takes it as vcf and throws out the error "Wrong vcf types".

**Comment by marcos-diazg** [comment]
Hi @Shukyo,

Many thanks for using our app! Please let me know a little bit more about your issue. When is the issue arisen, after uploading the files or after pressing the run button? MuSiCa error management takes into account the extension of the files to check for potential file format issues. Can you check that your MAF or TSV files had the right extension (.maf, .tsv or .txt)?

**Comment by marcos-diazg** [comment]
Close by inactivity and because the issue is not currently happening in the online version.
