### ISSUE TITLE
Web tool error with MAF file

### ISSUE THREAD

**Issue by paulinefx** [marcos-diazg/musica#43]
Hello,

I tried the web vesion of MuSiCa with a multi sample MAF file. However, I got an error : 

![image](https://user-images.githubusercontent.com/20558943/114048880-d9ab8880-9882-11eb-8be3-04c11c820cd3.png)

I emailed you, with the MAF file, but it got rejected by your email security, probably because of the MAF extension.

Could it be a problem with my MAF file ? I tried with one with only one sample and I got the same error.

Thank you for your help,

Pauline

**Comment by marcos-diazg** [comment]
Hi @paulinefx! So sorry for my late reply and thanks a lot for your interest. The email rejection is probably due to no longer having access to my previous email. Please let me know if you are still having this issue and if that's the case please send me your MAF file to my new email mdiazgay@health.ucsd.edu.

**Comment by marcos-diazg** [comment]
Hi again Pauline!

I was having a look at the code and I realized that there was a bug potentially affecting MAF files without a header with some lines starting with "#". It should be fixed now (for the local version of MuSiCa) in 350edcb87d0314f44db57976e30e6c1f3525af78. I hope this can solve your problem, please reopen the issue if that's not the case.

Remember that any MAF file that you want to use should have the columns "Chromosome", "Start_Position", "Reference_Allele", "Tumor_Seq_Allele2" and "Tumor_Sample_Barcode" with those specific names. You can always try the app with any of the open-access MAF files at https://portal.gdc.cancer.gov/.

Thanks again for your interest!

Best wishes,

Marcos
