### ISSUE TITLE
Online analysis failed: Disconnected from the server.

### ISSUE THREAD

**Issue by dshan25** [marcos-diazg/musica#45]
Hello, 

Thanks for making this useful tool.
I met an issue for online analysis. After I click "Run" (I tried vcf and tsp format, no problem with upload). I got "Disconnected from the server" on the screen and no results comes out. 

Thanks,
Shan

**Comment by marcos-diazg** [comment]
Dear @dshan25,

Thanks so much for your interest in our tool! We have been experiencing issues with our web server, so we have finally migrated the application to a new one. Please check the new URL below and let me know if you still have any issues. I will proceed to redirect all traffic to the new website in the following days.

https://toolsr.fcrb.es/sample-apps/MuSiCa/

Best regards,

Marcos

**Comment by dshan25** [comment]
Thanks so much for the quick reply, Marcos!

This website works well on most of my input lists.
However, when I upload larger file (i.e. 4.4M), I always get "error". (I double checked the format and there is no error.)
So I'm wondering is there a limitation of uploaded file size? 

Thanks a lot,
Shan

**Comment by marcos-diazg** [comment]
Dear @dshan25,

I'm glad that the new website worked fine for most of your data. We have a modest web server that cannot handle large files, so I suggest you install and use a local version for that purpose (as indicated in the README). You can also change your VCF or MAF files into TSV files (following the required file format), which should be much lighter in size.

I hope this helps, and thanks for your interest!

Marcos
