### ISSUE TITLE
Online version doesnt work

### ISSUE THREAD

**Issue by JanSliacky** [marcos-diazg/musica#48]
Submit button is missing.

**Comment by marcos-diazg** [comment]
Dear @JanSliacky,

I'm sorry, we are experiencing problems with our web server. However, we are currently working on a new version of the application that will be available in the next few months. In the meantime, you can use our app locally by following the instructions [here](https://github.com/marcos-diazg/musica#running-musica).

Please reopen the ticket if you have any questions or contact me by email at mdiazgay@ucsd.edu.
