### ISSUE TITLE
extendShinyjs error

### ISSUE THREAD

**Issue by mkazanov** [marcos-diazg/musica#49]
In bowser:
----------------
An error has occurred!
shinyjs: extendShinyjs: `functions` argument must not contain any of the following function names: refresh

In command line:
-----------------

$ echo 'shiny::runApp()' | Rscript -
Loading required package: shiny

Listening on http://127.0.0.1:5351

Attaching package: ‘shinysky’

The following object is masked from ‘package:shiny’:

    actionButton

Attaching package: ‘shinyjs’

The following object is masked from ‘package:shiny’:

    runExample

The following objects are masked from ‘package:methods’:

    removeClass, show

Using V8 engine 8.9.83
Loading required package: ggplot2

Attaching package: ‘plotly’

The following object is masked from ‘package:ggplot2’:

    last_plot

The following object is masked from ‘package:stats’:

    filter

The following object is masked from ‘package:graphics’:

    layout

Warning: Error in : shinyjs: extendShinyjs: `functions` argument must not contain any of the following function names:
refresh
  70: stop
  69: errMsg
  68: shinyjs::extendShinyjs
   1: shiny::runApp
Warning: Error in : shinyjs: extendShinyjs: `functions` argument must not contain any of the following function names:
refresh
  70: stop
  69: errMsg
  68: shinyjs::extendShinyjs
   1: shiny::runApp

**Comment by marcos-diazg** [comment]
Dear @mkazanov,

Thanks for your interest in our tool, and sorry for the delay in getting back to you. Please feel free to use our new tool, SigProfilerAssignment, which is available here: https://cancer.sanger.ac.uk/signatures/assignment/, and has been recently published: https://doi.org/10.1093/bioinformatics/btad756. Unfortunately, we are no longer supporting our legacy MuSiCa tool. Also, feel free to reach out to me by email (mdiazgay@ucsd.edu) if you have any further questions.

Best wishes,

Marcos
